version: '2'
plugins:
  rubocop:
    enabled: true
  eslint:
    enabled: false
    checks:
      function-paren-newline:
        enabled: false
exclude_patterns:
- "src/config/"
- "src/models/"
- "src/migrations/"
- "src/seeders/"
- "src/test/"